### ISSUE TITLE
Typos in two-loop VEV RGEs

### ISSUE THREAD

**Issue by TomSteu** [LSartore/pyrate#2]
Hi Lohan,

I think I found two typos in the RGEs for the VEV at two loop. I've compared the SM results to SARAH and find discrepancies that vanish in Landau gauge, which would explain why it has evaded your checks. The terms in question are `V2_1` and `V2_9`. If you compare the coefficients to eq. (12c) in  \[arXiv:1310.7629]{https://arxiv.org/abs/1310.7629} and set `ξ'=1` you will find that they should read `35/3 + 3/2*ξ  - 3/4*ξ²` and `-ξ` (accounting for the factor 1/2 difference in the definition of Y^2(S)), respectively.

**Comment by LSartore** [comment]
Hi Tom,
Thank you very much for looking into this. I'll correct the expressions right away !
Cheers,
Lohan
