### ISSUE TITLE
Possibility to fix indices in the model file?

### ISSUE THREAD

**Issue by TomSteu** [LSartore/pyrate#3]
Hi Lohan,

I hope you are doing well! 
I would like to share an idea for a feature, which however has both possible advantages and drawbacks. I would welcome comments from your side about its merit and feasibility within `PyR@TE3` -- I guess this is more a discussion than an issue. 

Is it possible to specify fixed gauge indices for fields directly in the model file, by inserting numbers inline?
For instance, one could specify a Yukawa vertex:
```
Qbar[2,c] H[2] dR[c]
```
If I am not mistaking, `PyR@TE` will interpret the `2` as an index to sum over as of the most recent version.

I imagine I should be technically possible to modify this behaviour such that fixed indices are evaluated before the contractions of tensor structures are resolved.

The obvious disadvantage is that it is very easy to violate gauge symmetry with this. I am not sure if and how gauge invariance can be checked if fixed indices are allowed. I would be up to the user to insure that the symmetry is intact, by adding all terms necessary by hand -- similar to `ARGES` and `RGBeta`.

The advantage of this would be that some structures could be implemented that are otherwise difficult. 
For instance: Take a SU(3) x SU(3) gauge symmetry, with a scalar field in the fundamental representation in both groups. There should be a cubic interaction term, that is just the determinant  of this 'matrix scalar'. I have no idea how to implement this other than specifying the indices directly. Or is there another way?

Overall, this is probably an antipattern of specifying a model file. I think in both `RGBeta` as well as `ARGES` there is a performance penalty in doing this. However, I am not certain how this impacts `PyR@TE`, but I suspect the situation is way less severe.
 
Anyways, let me know what you think, this is certainly not an urgent thing.

cheers,
Tom

**Comment by LSartore** [comment]
Hi Tom. Thank you very much for your question and suggestions.
Overall, specifying indices 'by hand' is something that I would prefer to avoid. However, I agree that there might be cases where this is necessary, or at least convenient. In your case, one possible alternative solution would be to express the determinant as a polynomial of traces of the matrix, using the Cayley-Hamilton theorem. In the case of a 3x3 matrix, one has:

![det](https://user-images.githubusercontent.com/50011969/118464146-cfda3800-b700-11eb-9bce-55bbcec999c7.png)

For larger matrices however, I expect this 'trick' to have poor performance. Implementing a way of computing the determinant of a 2-index tensor could be a good idea of improvement for future versions. I am also currently working on a possible new feature, allowing the user to implement arbitrarily complicated tensor objects and contractions using Python functions that can be directly called from the model file. With such a feature, the user would be able to either specify indices by hand, or create its own 'determinant' function.

I hope this helps!

Cheers,
Lohan

**Comment by TomSteu** [comment]
Hi Lohan,

yes, that is a very nice trick, I didn't think of that one! A little followup question: since `M` is bidoublet in a SU(3) x SU(3) gauge group, and your ansatz requires to write down contractions between left and right indices of M. Will such a contraction actually work, since it is between different gauge groups? 

Good to know you are looking into a possible enhancement, I'll stay tuned.

cheers,
Tom

**Comment by LSartore** [comment]
Hi Tom,

Yes. In principle the consistency checks only require indices to have the same range, so the above trick should work. However I didn't anticipate this and must say that I don't really like the idea of indices of different nature being contracted together.

Thinking a bit further about your cubic term, a more elegant solution would be to use the (built-in) 3-index Levi-Civita tensor to produce invariants out of three fundamental SU(3) reps. Namely, the following expression should in principle work :

`t : 1/6 * Eps[i,j,k] Eps[a,b,c] H[i,a] H[j,b] H[k,c]`

where the 1/6 factor is only needed to match the expression of the determinant.

Cheers,
Lohan

**Comment by TomSteu** [comment]
Ah, very good! I think my student was convinced `Eps` is only the rank two Levi-Civita symbol, I can convince him otherwise now.

Thanks!
