### ISSUE TITLE
ComplexPlot conflicts with Mathematica's built-in ComplexPlot

### ISSUE THREAD

**Issue by Yong-Du** [LSartore/pyrate#4]
"ComplexPlot" function in the Mathematica output file conflicts with Mathematica's built-in function "ComplexPlot". This function is newly defined in Mathematica 12. It is an easy fix by changing the function name "ComplexPlot" in "IO/Mathematica.py" into any other ones not conflicted with Mathematica's built-in symbols/function names.

**Comment by LSartore** [comment]
Thanks for reporting this! This is now fixed.
